"""load medicine detail with barcodes

Revision ID: ed185cac4d14
Revises: 
Create Date: 2023-04-11 16:43:39.448599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed185cac4d14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_detail',
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name_bg', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('sales_measure', sa.String(), nullable=True),
    sa.Column('medicine_name', sa.String(), nullable=True),
    sa.Column('atc_code', sa.String(), nullable=True),
    sa.Column('opiate', sa.String(), nullable=True),
    sa.Column('nhif_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('medicine_id')
    )
    op.create_table('medicine_barcode',
    sa.Column('barcode_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('barcode_1', sa.String(), nullable=True),
    sa.Column('barcode_2', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_detail.medicine_id'], ),
    sa.PrimaryKeyConstraint('barcode_id')
    )
    op.create_table('sespa_list',
    sa.Column('sespa_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('drug_id', sa.String(), nullable=True),
    sa.Column('atc_code', sa.String(), nullable=True),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('drug_trade_name', sa.String(), nullable=True),
    sa.Column('nhif_code', sa.String(), nullable=True),
    sa.Column('nscrlp_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.String(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('nscrlp_drug_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_detail.medicine_id'], ),
    sa.PrimaryKeyConstraint('sespa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sespa_list')
    op.drop_table('medicine_barcode')
    op.drop_table('medicine_detail')
    # ### end Alembic commands ###
